#!/bin/bash

# Manish Steel Furniture Deployment Instructions
# This file contains step-by-step instructions for deploying the application to Vercel

echo "===================================================="
echo "    MANISH STEEL FURNITURE DEPLOYMENT GUIDE         "
echo "===================================================="
echo ""
echo "STEP 1: FRONTEND DEPLOYMENT"
echo "------------------------"
echo "1. Log in to your Vercel account at https://vercel.com"
echo "2. Create a new project by linking your GitHub repository or uploading the manish-steel-final/build directory"
echo "3. Configure the following environment variables for the frontend:"
echo "   - REACT_APP_API_URL={your-backend-url}/api (e.g., https://manish-steel-api.vercel.app/api)"
echo "   - REACT_APP_FRONTEND_URL={your-frontend-url} (e.g., https://manish-steel-furniture.vercel.app)"
echo "   - REACT_APP_CLOUDINARY_CLOUD_NAME={your-cloudinary-cloud-name} (if using Cloudinary)"
echo "   - REACT_APP_CLOUDINARY_API_KEY={your-cloudinary-api-key} (if using Cloudinary)"
echo "4. Configure the following build and output settings for the frontend:"
echo "   - Build Command: npm run build"
echo "   - Output Directory: build"
echo "   - Install Command: npm install"
echo "   - Development Command: npm start"
echo "   - Root Directory: manish-steel-final (if deploying from the repository root)"
echo "5. Deploy the frontend project"
echo ""
echo "STEP 2: BACKEND DEPLOYMENT"
echo "------------------------"
echo "1. In Vercel, create a new project for the server directory"
echo "2. Configure the following environment variables for the backend:"
echo "   - NODE_ENV=production"
echo "   - PORT=5000 (Vercel will override this, but it's needed for local development)"
echo "   - MONGO_URI={your-mongodb-connection-string}"
echo "   - JWT_SECRET={your-secure-jwt-secret}"
echo "   - CLOUDINARY_CLOUD_NAME={your-cloudinary-cloud-name}"
echo "   - CLOUDINARY_API_KEY={your-cloudinary-api-key}"
echo "   - CLOUDINARY_API_SECRET={your-cloudinary-api-secret}"
echo "   - FRONTEND_URL={your-frontend-url} (e.g., https://manish-steel-furniture.vercel.app)"
echo "3. Configure the following build and output settings for the backend:"
echo "   - Build Command: npm install"
echo "   - Output Directory: ."
echo "   - Install Command: npm install"
echo "   - Development Command: npm run dev"
echo "   - Root Directory: server (if deploying from the repository root)"
echo "4. Deploy the backend project"
echo ""
echo "STEP 3: VERIFY DEPLOYMENT"
echo "------------------------"
echo "1. Visit your frontend URL to confirm the site is loading correctly"
echo "2. Test authentication functionality"
echo "3. Test API connections by navigating through products, galleries, etc."
echo "4. Verify image uploads and Cloudinary integration"
echo ""
echo "STEP 4: CUSTOM DOMAIN SETUP (OPTIONAL)"
echo "------------------------"
echo "1. Purchase or configure a domain for your website (e.g., manishsteelfurniture.com)"
echo "2. In Vercel's dashboard for your frontend project, go to 'Settings' > 'Domains'"
echo "3. Add your custom domain and follow the DNS configuration instructions"
echo "4. Update environment variables if needed to match your new domain names"
echo ""
echo "CONGRATULATIONS! Your Manish Steel Furniture website should be live!"
echo ""
